### ISSUE TITLE
Optimization for Gene Divs

### ISSUE THREAD

**Issue by schlagercollin** [schlagercollin/screen_analyzer#2]
For screens with 20k+ genes, the time to iterate through and append genediv boxes is fairly long. Is there a better way to iterate through genedict?

Perhaps export this work to a thread and display as acquired?

**Comment by bhavenp** [comment]
I'm not sure. Putting it on another thread should be helpful. We could also limit the number of boxes shown to the top 5000

**Comment by schlagercollin** [comment]
Limiting it is a good solution. It shouldn’t have a problem with 5000. I also think there are optimization possibilities with the jQuery. I think right now the browser is trying to “redraw” each box as it is added—as opposed to redrawing all at once at end. Just little details, but with 20k+ it adds up.
